command: ['python', 'main.py']

env:
  - name: 'DATABRICKS_SERVERLESS_COMPUTE_ID'
    value: 'auto'
  
  - name: 'UC_CATALOG_NAME'
    value: 'tpch'
  
  - name: 'UC_SCHEMA_NAME'
    value: 'bronze'
  
  - name: 'GROQ_API_KEY'
    valueFrom: groq
  
  - name: 'SUPABASE_URL'
    valueFrom: supabase_url
  
  - name: 'SUPABASE_KEY'
    valueFrom: supabase_key
  
  - name: 'GOOGLE_API_KEY'
    valueFrom: google
  
  - name: 'TAVILY_API_KEY'
    valueFrom: tavily
  
  - name: 'LANGSMITH_TRACING'
    value: 'true'
  
  - name: 'LANGSMITH_ENDPOINT'
    value: https://api.smith.langchain.com
  
  - name: 'LANGSMITH_API_KEY'
    valueFrom: langsmith
  
  - name: 'LANGSMITH_PROJECT'
    value: 'AgenticLakehouse (PROD)'